In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("sales_raw_500.xlsx - Sheet1.csv")
df.head()

   Order_ID Order_Date Customer Region  Product  Sales   Cost
0      1001  1/13/2023    Rohit  South   Mobile  23289  19118
1      1002  10/7/2023     Aman   West   Laptop   8905   5593
2      1003  11/5/2023    Rahul  South  Monitor  59987  39959
3      1004  2/19/2024    Rahul  South  Printer  49597  33892
4      1005  1/26/2024   Anjali  North   Laptop  54797  34468

In [3]:
df = df.drop_duplicates()

In [4]:
df.duplicated().sum()

0

In [5]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001  1/13/2023    Rohit  South   Mobile  23289  19118
1        1002  10/7/2023     Aman   West   Laptop   8905   5593
2        1003  11/5/2023    Rahul  South  Monitor  59987  39959
3        1004  2/19/2024    Rahul  South  Printer  49597  33892
4        1005  1/26/2024   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496  4/24/2023    Kiran  North  Printer  23434  16388
496      1497  6/27/2023   Anjali  South   Laptop  49007  35970
497      1498   5/8/2023     Aman   East   Tablet  19160  15636
498      1499        NaN    Pooja   West   Mobile  59266  44326
499      1500  10/7/2023    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [6]:
# Fix date column
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors ='coerce')

In [7]:
df.isnull().sum()

Order_ID       0
Order_Date    18
Customer       0
Region         0
Product        0
Sales          0
Cost           0
dtype: int64

In [8]:
df =df.dropna(subset=['Order_Date'])

In [9]:
df.isnull().sum()

Order_ID      0
Order_Date    0
Customer      0
Region        0
Product       0
Sales         0
Cost          0
dtype: int64

In [10]:
df['Profit'] = df['Sales']-df['Cost'] 
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

C:\Users\PC\AppData\Local\Temp\ipykernel_7280\954322732.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit'] = df['Sales']-df['Cost']
C:\Users\PC\AppData\Local\Temp\ipykernel_7280\954322732.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['Order_Date'].dt.year
C:\Users\PC\AppData\Local\Temp\ipykernel_7280\954322732.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['Order_Date'].dt.month

In [11]:
df.head()

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1

In [12]:
df.to_csv('Sales_CLeaned.csv', index=False)

In [27]:
import pandas as pd
from sqlalchemy import create_engine

In [29]:
df = pd.read_csv("Sales_CLeaned.csv")
df.head()

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1

In [31]:
engine = create_engine('mysql+pymysql://root:Fahadsidd$337@localhost:3306/Sales_db')

In [35]:
df.to_sql(name='sales_data',con=engine, if_exists='replace', index = False)

482